- name: Delete volume
  na_ontap_volume:
    state: absent
    name: "{{ user }}_{{ jobtype }}"
    vserver: "{{ vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
- name: Delete Snapshot
  na_ontap_snapshot:
    state: absent
    snapshot: "clone_{{ user }}_{{ jobtype }}.0"
    volume: "{{ master }}"
    vserver: "{{ vserver }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
    hostname: "{{ netapp_hostname }}"
- name: Delete Policy
  na_ontap_export_policy:
    state: absent
    name: "{{ user }}_{{ jobtype }}"
    vserver: "{{ vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
- name: create volume clone
  na_ontap_volume_clone:
    state: present
    vserver: "{{ vserver }}"
    parent_volume: "{{ master }}"
    volume: "{{ user }}_{{ jobtype }}"
    space_reserve: none
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
- name: Create Policy
  na_ontap_export_policy:
    state: present
    name: "{{ user }}_{{ jobtype }}"
    vserver: "{{ vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
- name: Setup rules
  na_ontap_export_policy_rule:
    state: present
    policy_name: "{{ user }}_{{ jobtype }}"
    vserver: "{{ vserver }}"
    client_match: "{{ client_match }}"
    ro_rule: sys
    rw_rule: sys
    super_user_security: sys
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
- name: mount volume
  na_ontap_volume:
    state: present
    name: "{{ user }}_{{ jobtype }}"
    policy: "{{ user }}_{{ jobtype }}"
    junction_path: "/{{ user }}_{{ jobtype }}"
    vserver: "{{ vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
